/**
 * Taiwan administrative address options.
 *
 * Source: Ministry of the Interior, National Land Surveying and Mapping Center (NLSC)
 * - County/city list: https://api.nlsc.gov.tw/other/ListCounty
 * - Township list (household registration): https://api.nlsc.gov.tw/other/ListTown1/{countyCode}
 * - Village list: https://api.nlsc.gov.tw/other/ListVillage/{countyCode}/{towncode01}
 *
 * Data files are generated under /public/data/taiwan-address so the app can
 * load townships and villages on demand instead of bundling all rows up front.
 *
 * Generated by: frontend/scripts/download-taiwan-address.mjs
 * Generated at: 2026-05-20T15:10:59.662Z
 */

export type Village = {
  id: string
  name: string
}

export type Township = {
  code: string
  code01: string
  name: string
}

export type County = {
  code: string
  code01: string
  name: string
}

export const TAIWAN_COUNTIES: County[] = [
  {
    "code": "A",
    "code01": "63000",
    "name": "臺北市"
  },
  {
    "code": "C",
    "code01": "10017",
    "name": "基隆市"
  },
  {
    "code": "F",
    "code01": "65000",
    "name": "新北市"
  },
  {
    "code": "H",
    "code01": "68000",
    "name": "桃園市"
  },
  {
    "code": "O",
    "code01": "10018",
    "name": "新竹市"
  },
  {
    "code": "J",
    "code01": "10004",
    "name": "新竹縣"
  },
  {
    "code": "K",
    "code01": "10005",
    "name": "苗栗縣"
  },
  {
    "code": "B",
    "code01": "66000",
    "name": "臺中市"
  },
  {
    "code": "N",
    "code01": "10007",
    "name": "彰化縣"
  },
  {
    "code": "M",
    "code01": "10008",
    "name": "南投縣"
  },
  {
    "code": "P",
    "code01": "10009",
    "name": "雲林縣"
  },
  {
    "code": "I",
    "code01": "10020",
    "name": "嘉義市"
  },
  {
    "code": "Q",
    "code01": "10010",
    "name": "嘉義縣"
  },
  {
    "code": "D",
    "code01": "67000",
    "name": "臺南市"
  },
  {
    "code": "E",
    "code01": "64000",
    "name": "高雄市"
  },
  {
    "code": "T",
    "code01": "10013",
    "name": "屏東縣"
  },
  {
    "code": "G",
    "code01": "10002",
    "name": "宜蘭縣"
  },
  {
    "code": "U",
    "code01": "10015",
    "name": "花蓮縣"
  },
  {
    "code": "V",
    "code01": "10014",
    "name": "臺東縣"
  },
  {
    "code": "X",
    "code01": "10016",
    "name": "澎湖縣"
  },
  {
    "code": "W",
    "code01": "09020",
    "name": "金門縣"
  },
  {
    "code": "Z",
    "code01": "09007",
    "name": "連江縣"
  }
]

export const COUNTY_NAMES: string[] = TAIWAN_COUNTIES.map(county => county.name)

const townshipsCache = new Map<string, Promise<Township[]>>()
const villagesCache = new Map<string, Promise<Village[]>>()
const roadsCache = new Map<string, Promise<string[]>>()

function getCountyByName(countyName: string | null | undefined): County | null {
  if (!countyName) return null
  return TAIWAN_COUNTIES.find(county => county.name === countyName) ?? null
}

async function fetchJson<T>(path: string): Promise<T> {
  return await $fetch<T>(path)
}

export async function loadTownships(countyName: string | null | undefined): Promise<Township[]> {
  const county = getCountyByName(countyName)
  if (!county) return []
  if (!townshipsCache.has(county.code)) {
    townshipsCache.set(
      county.code,
      fetchJson<Township[]>(`/data/taiwan-address/townships/${county.code}.json`),
    )
  }
  return townshipsCache.get(county.code) ?? []
}

export async function loadVillages(
  countyName: string | null | undefined,
  townshipName: string | null | undefined,
): Promise<string[]> {
  const county = getCountyByName(countyName)
  if (!county || !townshipName) return []
  const township = (await loadTownships(countyName)).find(item => item.name === townshipName)
  if (!township) return []
  const cacheKey = `${county.code}/${township.code01}`
  if (!villagesCache.has(cacheKey)) {
    villagesCache.set(
      cacheKey,
      fetchJson<Village[]>(`/data/taiwan-address/villages/${county.code}/${township.code01}.json`),
    )
  }
  const villages = await villagesCache.get(cacheKey)
  return villages?.map(village => village.name) ?? []
}

/**
 * 載入某鄉鎮市區的路名 / 街道清單（去重後的字串陣列）。
 *
 * 資料來源：中華郵政 3+2 碼郵遞區號（離線預生成），由
 * `frontend/scripts/download-taiwan-roads.mjs` 去重產出至
 * `/public/data/taiwan-address/roads/{countyCode}/{towncode01}.json`。
 *
 * 注意：路名資料尚未產出前，對應 JSON 檔不存在 → 靜默回傳空陣列，
 * 讓路名欄位退化為純自填（combobox 仍可手動輸入），不會讓畫面壞掉。
 */
export async function loadRoads(
  countyName: string | null | undefined,
  townshipName: string | null | undefined,
): Promise<string[]> {
  const county = getCountyByName(countyName)
  if (!county || !townshipName) return []
  const township = (await loadTownships(countyName)).find(item => item.name === townshipName)
  if (!township) return []
  const cacheKey = `${county.code}/${township.code01}`
  if (!roadsCache.has(cacheKey)) {
    roadsCache.set(
      cacheKey,
      fetchJson<unknown>(`/data/taiwan-address/roads/${county.code}/${township.code01}.json`)
        // 路名資料未產出時，dev server 會回傳 SPA fallback HTML（200）而非 404，
        // $fetch 不會 throw，回來的是字串 → 必須用 Array.isArray 擋掉，否則會逐字元當成路名。
        .then(data => (Array.isArray(data) ? (data as string[]) : []))
        .catch(() => [] as string[]),
    )
  }
  return roadsCache.get(cacheKey) ?? []
}
